version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
      POSTGRES_DB: authdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  auth:
    build: ./service-auth
    environment:
      DATABASE_URL: postgresql://authuser:authpass@db:5432/authdb
      SECRET_KEY: supersecretkey
    depends_on:
      - db
    ports:
      - "6000:5000"
    networks:
      - appnet

  library:
    build: ./service-lib
    ports:
      - "6001:5001"
    networks:
      - appnet

  frontend:
    build: ./front
    ports:
      - "8080:80"
    depends_on:
      - auth
      - library
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:

